/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function MedicineEye(props) {
  const { nodes, materials } = useGLTF('/models-3d/glaucoma/medicineEye.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.lableMedicine}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_1.geometry}
        material={materials.bodyMedicine}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_2.geometry}
        material={materials.headMedicine}
      />
    </group>
  )
}

useGLTF.preload('/models-3d/glaucoma/medicineEye.glb')