/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
    const { nodes, materials } = useGLTF('/models-3d/cataracts/surgical-tool-set.glb')
    return (
        <group {...props} dispose={null}>
            <group name="Scene">
                <group name="ScissorsT1" userData={{ name: 'ScissorsT1' }}>
                    <group name="ScisorsType1" userData={{ name: 'ScisorsType1' }}>
                        <mesh
                            name="ScissorsType1"
                            castShadow
                            receiveShadow
                            geometry={nodes.ScissorsType1.geometry}
                            material={materials.ForcepMaterial}
                            userData={{ name: 'ScissorsType1' }}
                        />
                    </group>
                </group>
                <group name="Scissors_T2" userData={{ name: 'Scissors_T2' }}>
                    <group name="ScissorsType2" userData={{ name: 'ScissorsType2' }}>
                        <mesh
                            name="ScissorrsType2"
                            castShadow
                            receiveShadow
                            geometry={nodes.ScissorrsType2.geometry}
                            material={materials.ForcepMaterial}
                            userData={{ name: 'ScissorrsType2' }}
                        />
                    </group>
                </group>
                <group name="Scissors_T3" userData={{ name: 'Scissors_T3' }}>
                    <group name="ScissorsType3" userData={{ name: 'ScissorsType3' }}>
                        <mesh
                            name="ScissorrsType3"
                            castShadow
                            receiveShadow
                            geometry={nodes.ScissorrsType3.geometry}
                            material={materials.ForcepMaterial}
                            userData={{ name: 'ScissorrsType3' }}
                        />
                    </group>
                </group>
                <group name="Syringes" userData={{ name: 'Syringes' }}>
                    <group name="Syringe" userData={{ name: 'Syringe' }}>
                        <mesh
                            name="SyringeOne"
                            castShadow
                            receiveShadow
                            geometry={nodes.SyringeOne.geometry}
                            material={materials.SyringeOneMaterial}
                            userData={{ name: 'SyringeOne' }}
                        />
                        <mesh
                            name="SyringeTube"
                            castShadow
                            receiveShadow
                            geometry={nodes.SyringeTube.geometry}
                            material={materials.SyringeTubeMaterial}
                            userData={{ name: 'SyringeTube' }}
                        />
                    </group>
                </group>
                <group name="SyringeCaps" userData={{ name: 'SyringeCaps' }}>
                    <mesh
                        name="SyringeCap"
                        castShadow
                        receiveShadow
                        geometry={nodes.SyringeCap.geometry}
                        material={materials.SyringeCapMaterial}
                        userData={{ name: 'SyringeCap' }}
                    />
                </group>
                <group name="Towels" userData={{ name: 'Towels' }}>
                    <mesh
                        name="Towel"
                        castShadow
                        receiveShadow
                        geometry={nodes.Towel.geometry}
                        material={materials.TowelMaterial}
                        userData={{ name: 'Towel' }}
                    />
                </group>
                <group name="Trays" userData={{ name: 'Trays' }}>
                    <mesh
                        name="Tray"
                        castShadow
                        receiveShadow
                        geometry={nodes.Tray.geometry}
                        material={materials.ForcepMaterial}
                        userData={{ name: 'Tray' }}
                    />
                </group>
                <group name="Forceps" userData={{ name: 'Forceps' }}>
                    <mesh
                        name="Forcep"
                        castShadow
                        receiveShadow
                        geometry={nodes.Forcep.geometry}
                        material={materials.ForcepMaterial}
                        userData={{ name: 'Forcep' }}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models-3d/cataracts/surgical-tool-set.glb')
